"""
Metadata operations for PDF files.

This module handles the generation of classification reports and the injection
of these reports into PDF metadata as page labels.
"""
import os
import json
import fitz

def generate_report(progress_data: dict) -> dict:
    """
    Generates a JSON report keyed by 1-indexed page numbers.
    
    Args:
        progress_data: A dictionary containing the progress status of each page,
                       typically loaded from progress.json. Keys are formatted as
                       "page_0", "page_1", etc.
                       
    Returns:
        A dictionary mapping 1-indexed page numbers (as strings) to their assigned
        category, reason, and any telemetry data.
    """
    report = {}
    for key, value in progress_data.items():
        if key.startswith("page_"):
            page_num_str = str(int(key.replace("page_", "")) + 1)
            
            if isinstance(value, dict) and value.get("status") == "error":
                report[page_num_str] = {
                    "category": "Failed",
                    "reason": value.get("error", "Unknown error"),
                    "telemetry": value.get("telemetry", {})
                }
            elif value == "error":
                report[page_num_str] = {
                    "category": "Failed",
                    "reason": "Unknown error",
                    "telemetry": {}
                }
            elif isinstance(value, dict):
                report[page_num_str] = {
                    "category": value.get("category", "Uncategorized"),
                    "reason": value.get("reason", ""),
                    "telemetry": value.get("telemetry", {})
                }
            else:
                report[page_num_str] = {
                    "category": "Uncategorized",
                    "reason": "Invalid status format",
                    "telemetry": {}
                }
    return report

def inject_pdf_metadata(input_pdf_path: str, output_pdf_path: str, report_data: dict) -> None:
    """
    Injects Page Labels into a PyMuPDF document using format "{page_num} - {category}".
    
    Args:
        input_pdf_path: Path to the original PDF file.
        output_pdf_path: Path where the modified PDF will be saved.
        report_data: Dictionary containing the classification report for each page,
                     generated by `generate_report`.
    """
    doc = fitz.open(input_pdf_path)
    
    rules = []
    toc = []
    for i in range(len(doc)):
        page_num_str = str(i + 1)
        page_info = report_data.get(page_num_str, {})
        category = page_info.get("category", "Uncategorized")
        
        prefix = f"{i + 1} - {category}"
        rules.append({"startpage": i, "prefix": prefix, "style": ""})
        
        # Add to Table of Contents (Bookmarks)
        # format: [level, title, page_number] where page_number is 1-indexed
        toc.append([1, prefix, i + 1])
        
    doc.set_page_labels(rules)
    doc.set_toc(toc)
    doc.save(output_pdf_path)
    doc.close()
